FROM oven/bun:1.3.14-alpine

# Install FFmpeg & Python dependencies
RUN apk add --no-cache ffmpeg python3 make g++

WORKDIR /app

# Copy root package files
COPY package.json bun.lock ./
COPY server/package.json ./server/

# Install dependencies
RUN bun install

# Copy application source
COPY . .

EXPOSE 4000

CMD ["bun", "run", "server/src/index.ts"]
